from django.urls import path
from .import views 
urlpatterns = [
    path('',views.charity_login,name='login'),
    path('Dashboard/',views.charity_dashboard_new_user,name='dashboardNew'),
    path('dashboard/',views.charity_dashboard_old_user,name='dashboardOld'),
    path('zakahTypes/',views.ADDZakahTypes,name='zakahTypes'),
    path('profile/',views.charity_profile,name='charityPprofile'),
    path('dashboard/delete',views.delete_zakah_type,name='delete_zakah_type'),
    path('dashboard/add',views.ADD_zakah_type,name='add_zakah_type'),
    # path('dashboard/editDev4char',views.edit_dev_from_side_charity,name='edit_dev_from_side_charity'),
    path('dashboard/dispalyDev4char',views.display_device_4charity,name='display_device_4charity'),
    path('dashboard/senddate',views.charity_dashboard_old_user,name='between2Dates_Statistics'),
    path('dashboard/sendmonth',views.charity_dashboard_old_user,name='filtermonth_Statistics'),
    path('admindashboard',views.AdminDashboard,name='AdminDash'),
    path('admindashboard/addchar',views.add_Charity,name='add_Charity'),
    path('admindashboard/displayzakah',views.displayZakah,name='displayzakah'),
    path('admindashboard/editZakah',views.edit_Zakah,name='edit_zakah'),
    path('admindashboard/deleteZakah',views.delete_zakah,name='delete_zakah'),
    path('admindashboard/deletechar',views.delete_charity,name='delete_charity'),
    path('admindashboard/addDevice',views.add_Dev,name='add_Dev'),
    path('admindashboard/deletedev',views.delete_Device,name='delete_Dev'),
    path('admindashboard/assigndev',views.assign_Device,name='ass_Dev'),
    path('admindashboard/editchar',views.Edit_charity,name='edit_charity'),
    path('admindashboard/addSubZakah',views.AddSubZakah,name='addSubZakah'),
    path('logout',views.logout,name='logout'),
    path('dashboard/addzakahch',views.AddZakahFromCharitySide,name='addzakah4ch'),
    path('subzakah/',views.subzakah4admin,name='addzakah4ch'),
    #path('subzakah/<str:name>',views.subzakah4admin,name='addzakah4ch'),
    path('deletesub/',views.delete_subzakah4admin,name='deletesub'),
    path('editsub/',views.edit_subzakah,name='editsub'),
    path('addsub4type/',views.addSubzahah4SpecialType,name='addsub4type'),
    path('addothersub4char/',views.addOtherSubZakah4charity,name='addothersub4char'),
    path('dashboard/addsub',views.addSubzakah4charity,name='add_zakah_subtype'),
    path('subzakah4charity/',views.viewsubzakah4charity,name='subzakah4charity'),
    path('deletesub4charity/',views.delete_subzakah,name='deletesub4charity'),
    path('editsub4type4char/',views.edit_subzakah4type4charity,name='editsub4type4char'),
    path('addsub4type4char/',views.add_subzakah4type4charity,name='addsub4type4char'),
    path('dashboard/devstatistics/',views.statistics4OneDevice,name='devicestatistics'),

]
