# Generated by Django 3.2.7 on 2021-09-28 18:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakah_Device', '0002_alter_transaction_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 28, 22, 55, 27, 467785)),
        ),
    ]
