# Generated by Django 4.1.7 on 2023-03-26 08:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakah_Device', '0003_alter_transaction_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='types',
            name='_id',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 12, 10, 24, 309417)),
        ),
    ]
